<a href="https://colab.research.google.com/github/tatipara/eleicao_2026_1turno/blob/main/aAsbten%C3%A7%C3%A3os_eleicao2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from pathlib import Path

# Pasta principal
BASE = Path("/content/tse2026")

# Subpastas
RAW = BASE / "raw"
CSV = BASE / "csv"
MAPAS = BASE / "mapas"
ZIPS = BASE / "zips"

# Cria tudo automaticamente
for pasta in [BASE, RAW, CSV, MAPAS, ZIPS]:
    pasta.mkdir(parents=True, exist_ok=True)

print("Estrutura criada:")

for pasta in [BASE, RAW, CSV, MAPAS, ZIPS]:
    print("✓", pasta)

Estrutura criada:
✓ /content/tse2026
✓ /content/tse2026/raw
✓ /content/tse2026/csv
✓ /content/tse2026/mapas
✓ /content/tse2026/zips

Baixando dados do TSE - ELEITORADO E LOCAIS DE VOTAÇÃO

In [3]:
import requests
import zipfile
import io
import pandas as pd

# --------------------------------------------------
# DOWNLOADS
# --------------------------------------------------

URL_LOCAIS = (
    "https://cdn.tse.jus.br/estatistica/sead/odsele/"
    "eleitorado_locais_votacao/"
    "eleitorado_local_votacao_2026.zip"
)

URL_VOTOS = (
    "https://cdn.tse.jus.br/estatistica/sead/odsele/"
    "votacao_secao/"
    "votacao_secao_2026_BR.zip"
)

print("Baixando locais...")
resp_locais = requests.get(URL_LOCAIS, timeout=120)

print("Baixando votação...")
resp_votos = requests.get(URL_VOTOS, timeout=120)

print("Status locais:", resp_locais.status_code)
print("Status votos :", resp_votos.status_code)

zf_locais = zipfile.ZipFile(io.BytesIO(resp_locais.content))
zf_votos = zipfile.ZipFile(io.BytesIO(resp_votos.content))

print("\nArquivos locais:")
print(zf_locais.namelist())

print("\nArquivos votação:")
print(zf_votos.namelist())

Baixando locais...
Baixando votação...
Status locais: 200
Status votos : 200

Arquivos locais:
['eleitorado_local_votacao_2026_MT.csv', 'eleitorado_local_votacao_2026_PA.csv', 'eleitorado_local_votacao_2026_GO.csv', 'eleitorado_local_votacao_2026_MS.csv', 'eleitorado_local_votacao_2026_MG.csv', 'eleitorado_local_votacao_2026_PB.csv', 'eleitorado_local_votacao_2026_MA.csv', 'eleitorado_local_votacao_2026_AL.csv', 'eleitorado_local_votacao_2026_AC.csv', 'eleitorado_local_votacao_2026_AM.csv', 'eleitorado_local_votacao_2026_CE.csv', 'eleitorado_local_votacao_2026_AP.csv', 'eleitorado_local_votacao_2026_BA.csv', 'eleitorado_local_votacao_2026_DF.csv', 'eleitorado_local_votacao_2026_ES.csv', 'eleitorado_local_votacao_2026_TO.csv', 'eleitorado_local_votacao_2026_BRASIL.csv', 'eleitorado_local_votacao_2026_PE.csv', 'eleitorado_local_votacao_2026_SE.csv', 'eleitorado_local_votacao_2026_PI.csv', 'eleitorado_local_votacao_2026_PR.csv', 'eleitorado_local_votacao_2026_RN.csv', 'eleitorado_local_votacao_2026_SC.csv', 'eleitorado_local_votacao_2026_RJ.csv', 'eleitorado_local_votacao_2026_RO.csv', 'eleitorado_local_votacao_2026_RS.csv', 'eleitorado_local_votacao_2026_RR.csv', 'eleitorado_local_votacao_2026_ZZ.csv', 'eleitorado_local_votacao_2026_SP.csv', 'leiame.pdf']

Arquivos votação:
['votacao_secao_2026_BR.csv', 'leiame.pdf']

Visualizar o eleitorado

In [4]:
print("\nLendo eleitorado...")

with zf_locais.open(
    "eleitorado_local_votacao_2026_BRASIL.csv"
) as f:

    eleitorado = pd.read_csv(
        f,
        sep=";",
        encoding="latin1",
        usecols=[
            "SG_UF",
            "CD_MUNICIPIO",
            "NM_MUNICIPIO",
            "NR_ZONA",
            "NR_SECAO",
            "NR_LOCAL_VOTACAO",
            "NM_LOCAL_VOTACAO",
            "QT_ELEITOR_ELEICAO_FEDERAL"
        ]
    )

print(eleitorado.shape)

display(eleitorado.head())

Lendo eleitorado...
(1034358, 8)

,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_SECAO,NR_LOCAL_VOTACAO,NM_LOCAL_VOTACAO,QT_ELEITOR_ELEICAO_FEDERAL
0,SP,69795,RIO CLARO,288,204,1228,EM JOVELINA MORATELI,393
1,SP,67890,OSASCO,276,124,1066,EE. PROFª. MARIA AUGUSTA SIQUEIRA,299
2,SP,67890,OSASCO,276,92,1090,EE. PROF. ALCYR OLIVEIRA PORCIÚNCULA,349
3,BA,35130,EUCLIDES DA CUNHA,102,40,1074,COLÉGIO MODELO JOAQUIM SILVA DANTAS,272
4,SP,66397,LIMEIRA,66,437,1660,CENTRO EDUCACIONAL SESI 408,335

Visualizar o local de votação

In [5]:
print("\nLendo votação...")

with zf_votos.open(
    "votacao_secao_2026_BR.csv"
) as f:

    votos = pd.read_csv(
        f,
        sep=";",
        encoding="latin1",
        usecols=[
            "SG_UF",
            "CD_MUNICIPIO",
            "NR_ZONA",
            "NR_SECAO",
            "NR_LOCAL_VOTACAO",
            "NM_LOCAL_VOTACAO",
            "NM_VOTAVEL",
            "QT_VOTOS"
        ]
    )

print(votos.shape)

display(votos.head())

Lendo votação...
(3800511, 8)

,SG_UF,CD_MUNICIPIO,NR_ZONA,NR_SECAO,NM_VOTAVEL,QT_VOTOS,NR_LOCAL_VOTACAO,NM_LOCAL_VOTACAO
0,RS,86363,101,105,ROMEU ZEMA NETO,1,1074,ESC. EST. JOAO LEOPOLDO VOGT
1,RS,86363,101,105,LUIZ INÁCIO LULA DA SILVA,129,1074,ESC. EST. JOAO LEOPOLDO VOGT
2,RS,85251,92,36,LUIZ INÁCIO LULA DA SILVA,130,1287,EEEF MARIA DA SILVA SOARES - ESCOLA ROTARY
3,RS,85960,62,22,LUIZ INÁCIO LULA DA SILVA,38,1341,SALÃO COMUNITÁRIO DE TUNAS
4,RS,85790,140,88,LUIZ INÁCIO LULA DA SILVA,64,1163,ESCOLA ESTADUAL DE ENSINO MÉDIO SÃO FRANCISCO ...

Conferir Brancos e nulos

In [6]:
print(
    votos["NM_VOTAVEL"]
    .drop_duplicates()
    .sort_values()
    .tolist()
)

['AUGUSTO JORGE CURY', 'CLARIANA ZACARKIM BARAO', 'EDMILSON SILVA COSTA', 'FLAVIO NANTES BOLSONARO', 'HERTZ DA CONCEICAO DIAS', 'LEONARDO ALVES DE ARAUJO', 'LUIZ INÁCIO LULA DA SILVA', 'RENAN ANTONIO FERREIRA DOS SANTOS', 'ROMEU ZEMA NETO', 'RONALDO RAMOS CAIADO', 'RUI COSTA PIMENTA', 'SAMARA MARTINS DA SILVA FEITOSA', 'VOTO BRANCO', 'VOTO NULO', 'WILSON GRASSI JUNIOR']

Verificar quem compareceu para votar

In [7]:
comparecimento = (

    votos

    .groupby(
        [
            "SG_UF",
            "CD_MUNICIPIO",
            "NR_ZONA",
            "NR_SECAO",
            "NR_LOCAL_VOTACAO",
            "NM_LOCAL_VOTACAO"
        ],
        as_index=False
    )

    ["QT_VOTOS"]

    .sum()

)

comparecimento.rename(
    columns={
        "QT_VOTOS":"COMPARECIMENTO"
    },
    inplace=True
)

print(comparecimento.shape)

display(comparecimento.head())

(499206, 7)

,SG_UF,CD_MUNICIPIO,NR_ZONA,NR_SECAO,NR_LOCAL_VOTACAO,NM_LOCAL_VOTACAO,COMPARECIMENTO
0,AC,1007,9,1,1104,ESCOLA EDMUNDO PINTO DE ALMEIDA NETO,241
1,AC,1007,9,2,1104,ESCOLA EDMUNDO PINTO DE ALMEIDA NETO,240
2,AC,1007,9,3,1104,ESCOLA EDMUNDO PINTO DE ALMEIDA NETO,242
3,AC,1007,9,4,1104,ESCOLA EDMUNDO PINTO DE ALMEIDA NETO,244
4,AC,1007,9,5,1112,ESCOLA SÃO JOÃO BATISTA,251

Calcular, então , a Abstenção

In [8]:
abstencao = eleitorado.merge(

    comparecimento,

    on=[
        "SG_UF",
        "CD_MUNICIPIO",
        "NR_ZONA",
        "NR_SECAO",
        "NR_LOCAL_VOTACAO",
        "NM_LOCAL_VOTACAO"
    ],

    how="left"
)

abstencao["COMPARECIMENTO"] = (
    abstencao["COMPARECIMENTO"]
    .fillna(0)
)

abstencao["ABSTENCAO"] = (

    abstencao["QT_ELEITOR_ELEICAO_FEDERAL"]

    -

    abstencao["COMPARECIMENTO"]

)

abstencao["PCT_ABSTENCAO"] = (

    100

    *

    abstencao["ABSTENCAO"]

    /

    abstencao["QT_ELEITOR_ELEICAO_FEDERAL"]

).round(2)

print(abstencao.shape)

display(abstencao.head())

(1034358, 11)

,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_SECAO,NR_LOCAL_VOTACAO,NM_LOCAL_VOTACAO,QT_ELEITOR_ELEICAO_FEDERAL,COMPARECIMENTO,ABSTENCAO,PCT_ABSTENCAO
0,SP,69795,RIO CLARO,288,204,1228,EM JOVELINA MORATELI,393,320.0,73.0,18.58
1,SP,67890,OSASCO,276,124,1066,EE. PROFª. MARIA AUGUSTA SIQUEIRA,299,243.0,56.0,18.73
2,SP,67890,OSASCO,276,92,1090,EE. PROF. ALCYR OLIVEIRA PORCIÚNCULA,349,283.0,66.0,18.91
3,BA,35130,EUCLIDES DA CUNHA,102,40,1074,COLÉGIO MODELO JOAQUIM SILVA DANTAS,272,229.0,43.0,15.81
4,SP,66397,LIMEIRA,66,437,1660,CENTRO EDUCACIONAL SESI 408,335,276.0,59.0,17.61

Juntar com dados da escola/local de votação - Por CIDADES

In [9]:
abstencao_local = (

    abstencao

    .groupby(
        [
            "SG_UF",
            "CD_MUNICIPIO",
            "NM_MUNICIPIO",
            "NR_LOCAL_VOTACAO",
            "NM_LOCAL_VOTACAO"
        ],
        as_index=False
    )

    .agg(
        {
            "QT_ELEITOR_ELEICAO_FEDERAL":"sum",
            "COMPARECIMENTO":"sum",
            "ABSTENCAO":"sum"
        }
    )

)

abstencao_local["PCT_ABSTENCAO"] = (

    100

    *

    abstencao_local["ABSTENCAO"]

    /

    abstencao_local["QT_ELEITOR_ELEICAO_FEDERAL"]

).round(2)

display(
    abstencao_local
    .sort_values(
        "QT_ELEITOR_ELEICAO_FEDERAL",
        ascending=False
    )
    .head(20)
)

,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_LOCAL_VOTACAO,NM_LOCAL_VOTACAO,QT_ELEITOR_ELEICAO_FEDERAL,COMPARECIMENTO,ABSTENCAO,PCT_ABSTENCAO
96621,ZZ,30341,PORTO,1015,ISEP - R. DR. ANTONIO BERNARDINO / R. DE SÃO T...,90978,38440.0,52538.0,57.75
96496,ZZ,29955,LISBOA,1031,"UNIVERSIDADE DE LISBOA (REITORIA, FAC. DIREITO...",83550,24510.0,59040.0,70.66
96541,ZZ,30112,MIAMI,1058,MIAMI DADE COLLEGE - KENDALL CAMPUS,80113,24556.0,55557.0,69.35
96600,ZZ,30228,NOVA YORK,1082,QUEENS COLLEGE,77905,20268.0,57637.0,73.98
96506,ZZ,29971,LONDRES,1015,WEST LONDON COLLEGE,74911,29594.0,45317.0,60.49
96497,ZZ,29955,LISBOA,1080,"UNIVERSIDADE DE LISBOA (REITORIA, FAC. DIREITO...",73681,32776.0,40905.0,55.52
96365,ZZ,29416,BOSTON,1023,SALEMWOOD SCHOOL,69770,22200.0,47570.0,68.18
96577,ZZ,30198,NAGÓIA,1015,"GIFU MEMORIAL CENTER, DEAI DOME E FUREAI DOME",55727,18172.0,37555.0,67.39
96615,ZZ,30287,PARIS,1066,ESPACE VINCI,53914,21080.0,32834.0,60.90
96779,ZZ,99490,ORLANDO,1015,OSCEOLA HERITAGE PARK,52773,17988.0,34785.0,65.91
96543,ZZ,30120,MILÃO,1040,SELEXI TEST CENTER,49192,14910.0,34282.0,69.69
96526,ZZ,30066,MADRI,1023,COLÉGIO BLANCA DE CASTILLA,46928,13666.0,33262.0,70.88
96699,ZZ,30635,TORONTO,1066,YMCA CENTRE-TORONTO - ONTÁRIO,40270,17006.0,23264.0,57.77
96706,ZZ,30783,WASHINGTON,1031,CAPITAL HILTON (HOTEL),36301,9672.0,26629.0,73.36
92232,SP,71072,SÃO PAULO,1023,PUC - PONTIFÍCIA UNIVERSIDADE CATÓLICA,35111,26806.0,8305.0,23.65
96680,ZZ,30627,TÓQUIO,1023,ARIAKE CENTRAL TOWER,35080,13420.0,21660.0,61.74
96343,ZZ,29351,BARCELONA,1015,SEMINARI CONCILIAR DE BARCELONA,34508,10370.0,24138.0,69.95
96422,ZZ,29661,DUBLIN,1015,ROYAL DUBLIN SOCIETY - HALL 2,33445,16834.0,16611.0,49.67
53356,PE,24570,JABOATÃO DOS GUARARAPES,1740,FACULDADE DOS GUARARAPES - UNIFG,32830,25802.0,7028.0,21.41
96739,ZZ,39080,ATLANTA,1015,EAGLES ARENA,32603,10044.0,22559.0,69.19

In [10]:
abstencao_local.to_csv(

    "/content/tse2026/abstencao_por_escola.csv",

    index=False,

    encoding="utf-8-sig"

)

print(
    "Arquivo salvo:"
)

print(
    "/content/tse2026/abstencao_por_escola.csv"
)

Arquivo salvo:
/content/tse2026/abstencao_por_escola.csv

In [11]:
abstencao_local[
[
    "NM_LOCAL_VOTACAO",
    "QT_ELEITOR_ELEICAO_FEDERAL",
    "COMPARECIMENTO",
    "ABSTENCAO",
    "PCT_ABSTENCAO"
]
].head(30)

,NM_LOCAL_VOTACAO,QT_ELEITOR_ELEICAO_FEDERAL,COMPARECIMENTO,ABSTENCAO,PCT_ABSTENCAO
0,ESCOLA JOSE CEZARIO DE FARIAS,2866,2204.0,662.0,23.10
1,ESCOLA MAPINGUARI - FUNTAC - PROJETO ANTIMARI,422,312.0,110.0,26.07
2,"NÚCLEO DE EDUCAÇÃO, CULTURA E ESPORTES - SEE -...",1853,1464.0,389.0,20.99
3,ESCOLA RURAL NOVA VIDA,916,750.0,166.0,18.12
4,ESCOLA RURAL MARIA DO CARMO RAMOS,708,514.0,194.0,27.40
5,SEPA - SECRETARIA DE ESTADO DE PRODUÇÃO E AGRO...,1244,968.0,276.0,22.19
6,CRECHE PROFESSORA DONA BELA,1452,1114.0,338.0,23.28
7,ESCOLA EDMUNDO PINTO DE ALMEIDA NETO,4822,3702.0,1120.0,23.23
8,ESCOLA SÃO JOÃO BATISTA,5862,4608.0,1254.0,21.39
9,ESCOLA ESTADUAL PEDRO GOMES,1732,1334.0,398.0,22.98
10,UNIDADE DE GESTÃO AMBIENTAL INTEGRADA - UGAI,428,344.0,84.0,19.63
11,ESCOLA ARGENTINA PEREIRA FEITOSA,3912,3138.0,774.0,19.79
12,ESCOLA NAIR SOMBRA,2490,2052.0,438.0,17.59
13,PRE-ESCOLA MUNDO ENCANTADO,2246,1798.0,448.0,19.95
14,ESCOLA NOVA ESPERANCA,2342,1776.0,566.0,24.17
15,ESCOLA MUNICIPAL RURAL SÃO FRANCISCO,540,458.0,82.0,15.19
16,ESCOLA MUNICIPAL MARIETA FREIRE RODRIGUES,392,0.0,392.0,100.00
17,ESC ENS FUN PROF NOELIA MARIA ALVES DE SOUZA,2926,2050.0,876.0,29.94
18,ESCOLA MUNICIPAL MARIA FERNANDES DE AMORIM,252,212.0,40.0,15.87
19,ESCOLA ARISTON FERREIRA DA CUNHA,1242,998.0,244.0,19.65
20,ESCOLA JOSE PLACIDO DE CASTRO,3629,2936.0,693.0,19.10
21,ESCOLA EDMUNDO PINTO DE ALMEIDA NETO,3740,3134.0,606.0,16.20
22,ESCOLA PUBLICA JADER SARAIVA MACHADO,4426,3624.0,802.0,18.12
23,ESCOLA NOSSA SENHORA AUXILIADORA,654,550.0,104.0,15.90
24,ESCOLA MAJOR WENCESLAU SALINAS,1598,1284.0,314.0,19.65
25,ESCOLA MUNICIPAL JOAQUIM FALCAO MACEDO,916,746.0,170.0,18.56
26,ESCOLA MUNICIPAL NOVO HORIZONTE,3534,2850.0,684.0,19.35
27,UNIDADE DE SAÚDE DA FAMÍLIA ILDA BARBOSA DE SOUZA,888,734.0,154.0,17.34
28,ESCOLA SÃO RAIMUNDO NONATO,936,720.0,216.0,23.08
29,CENTRO CULTURAL DA FLORESTANIA,0,0.0,0.0,NaN

In [12]:
with open(
    "/content/tse2026/zips/eleitorado_local_votacao_2026.zip",
    "wb"
) as f:
    f.write(resp_locais.content)

print("ZIP de locais salvo")

ZIP de locais salvo

In [13]:
abstencao_local.to_csv(
    "/content/tse2026/csv/abstencao_por_escola.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Arquivo salvo:")
print("/content/tse2026/csv/abstencao_por_escola.csv")

Arquivo salvo:
/content/tse2026/csv/abstencao_por_escola.csv

In [14]:
print(abstencao_local.shape)

display(
    abstencao_local.head(20)
)

display(
    abstencao_local.sort_values(
        "QT_ELEITOR_ELEICAO_FEDERAL",
        ascending=False
    ).head(20)
)

(96788, 9)

,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_LOCAL_VOTACAO,NM_LOCAL_VOTACAO,QT_ELEITOR_ELEICAO_FEDERAL,COMPARECIMENTO,ABSTENCAO,PCT_ABSTENCAO
0,AC,1007,BUJARI,1023,ESCOLA JOSE CEZARIO DE FARIAS,2866,2204.0,662.0,23.10
1,AC,1007,BUJARI,1040,ESCOLA MAPINGUARI - FUNTAC - PROJETO ANTIMARI,422,312.0,110.0,26.07
2,AC,1007,BUJARI,1058,"NÚCLEO DE EDUCAÇÃO, CULTURA E ESPORTES - SEE -...",1853,1464.0,389.0,20.99
3,AC,1007,BUJARI,1066,ESCOLA RURAL NOVA VIDA,916,750.0,166.0,18.12
4,AC,1007,BUJARI,1074,ESCOLA RURAL MARIA DO CARMO RAMOS,708,514.0,194.0,27.40
5,AC,1007,BUJARI,1082,SEPA - SECRETARIA DE ESTADO DE PRODUÇÃO E AGRO...,1244,968.0,276.0,22.19
6,AC,1007,BUJARI,1090,CRECHE PROFESSORA DONA BELA,1452,1114.0,338.0,23.28
7,AC,1007,BUJARI,1104,ESCOLA EDMUNDO PINTO DE ALMEIDA NETO,4822,3702.0,1120.0,23.23
8,AC,1007,BUJARI,1112,ESCOLA SÃO JOÃO BATISTA,5862,4608.0,1254.0,21.39
9,AC,1007,BUJARI,1120,ESCOLA ESTADUAL PEDRO GOMES,1732,1334.0,398.0,22.98
10,AC,1007,BUJARI,1147,UNIDADE DE GESTÃO AMBIENTAL INTEGRADA - UGAI,428,344.0,84.0,19.63
11,AC,1015,CAPIXABA,1015,ESCOLA ARGENTINA PEREIRA FEITOSA,3912,3138.0,774.0,19.79
12,AC,1015,CAPIXABA,1023,ESCOLA NAIR SOMBRA,2490,2052.0,438.0,17.59
13,AC,1015,CAPIXABA,1058,PRE-ESCOLA MUNDO ENCANTADO,2246,1798.0,448.0,19.95
14,AC,1015,CAPIXABA,1066,ESCOLA NOVA ESPERANCA,2342,1776.0,566.0,24.17
15,AC,1015,CAPIXABA,1104,ESCOLA MUNICIPAL RURAL SÃO FRANCISCO,540,458.0,82.0,15.19
16,AC,1015,CAPIXABA,1112,ESCOLA MUNICIPAL MARIETA FREIRE RODRIGUES,392,0.0,392.0,100.00
17,AC,1015,CAPIXABA,1120,ESC ENS FUN PROF NOELIA MARIA ALVES DE SOUZA,2926,2050.0,876.0,29.94
18,AC,1015,CAPIXABA,1228,ESCOLA MUNICIPAL MARIA FERNANDES DE AMORIM,252,212.0,40.0,15.87
19,AC,1015,CAPIXABA,1236,ESCOLA ARISTON FERREIRA DA CUNHA,1242,998.0,244.0,19.65

,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_LOCAL_VOTACAO,NM_LOCAL_VOTACAO,QT_ELEITOR_ELEICAO_FEDERAL,COMPARECIMENTO,ABSTENCAO,PCT_ABSTENCAO
96621,ZZ,30341,PORTO,1015,ISEP - R. DR. ANTONIO BERNARDINO / R. DE SÃO T...,90978,38440.0,52538.0,57.75
96496,ZZ,29955,LISBOA,1031,"UNIVERSIDADE DE LISBOA (REITORIA, FAC. DIREITO...",83550,24510.0,59040.0,70.66
96541,ZZ,30112,MIAMI,1058,MIAMI DADE COLLEGE - KENDALL CAMPUS,80113,24556.0,55557.0,69.35
96600,ZZ,30228,NOVA YORK,1082,QUEENS COLLEGE,77905,20268.0,57637.0,73.98
96506,ZZ,29971,LONDRES,1015,WEST LONDON COLLEGE,74911,29594.0,45317.0,60.49
96497,ZZ,29955,LISBOA,1080,"UNIVERSIDADE DE LISBOA (REITORIA, FAC. DIREITO...",73681,32776.0,40905.0,55.52
96365,ZZ,29416,BOSTON,1023,SALEMWOOD SCHOOL,69770,22200.0,47570.0,68.18
96577,ZZ,30198,NAGÓIA,1015,"GIFU MEMORIAL CENTER, DEAI DOME E FUREAI DOME",55727,18172.0,37555.0,67.39
96615,ZZ,30287,PARIS,1066,ESPACE VINCI,53914,21080.0,32834.0,60.90
96779,ZZ,99490,ORLANDO,1015,OSCEOLA HERITAGE PARK,52773,17988.0,34785.0,65.91
96543,ZZ,30120,MILÃO,1040,SELEXI TEST CENTER,49192,14910.0,34282.0,69.69
96526,ZZ,30066,MADRI,1023,COLÉGIO BLANCA DE CASTILLA,46928,13666.0,33262.0,70.88
96699,ZZ,30635,TORONTO,1066,YMCA CENTRE-TORONTO - ONTÁRIO,40270,17006.0,23264.0,57.77
96706,ZZ,30783,WASHINGTON,1031,CAPITAL HILTON (HOTEL),36301,9672.0,26629.0,73.36
92232,SP,71072,SÃO PAULO,1023,PUC - PONTIFÍCIA UNIVERSIDADE CATÓLICA,35111,26806.0,8305.0,23.65
96680,ZZ,30627,TÓQUIO,1023,ARIAKE CENTRAL TOWER,35080,13420.0,21660.0,61.74
96343,ZZ,29351,BARCELONA,1015,SEMINARI CONCILIAR DE BARCELONA,34508,10370.0,24138.0,69.95
96422,ZZ,29661,DUBLIN,1015,ROYAL DUBLIN SOCIETY - HALL 2,33445,16834.0,16611.0,49.67
53356,PE,24570,JABOATÃO DOS GUARARAPES,1740,FACULDADE DOS GUARARAPES - UNIFG,32830,25802.0,7028.0,21.41
96739,ZZ,39080,ATLANTA,1015,EAGLES ARENA,32603,10044.0,22559.0,69.19

EXEMPLOS PARA BRASÍLIA - TROQUE A UF para verificar no seu estado

In [15]:
df = abstencao_local[
    abstencao_local["SG_UF"] == "DF"
]

display(
    df[
        [
            "NM_LOCAL_VOTACAO",
            "QT_ELEITOR_ELEICAO_FEDERAL",
            "COMPARECIMENTO",
            "ABSTENCAO",
            "PCT_ABSTENCAO"
        ]
    ]
    .sort_values(
        "QT_ELEITOR_ELEICAO_FEDERAL",
        ascending=False
    )
    .head(50)
)

,NM_LOCAL_VOTACAO,QT_ELEITOR_ELEICAO_FEDERAL,COMPARECIMENTO,ABSTENCAO,PCT_ABSTENCAO
20493,CENTRO UNIVERSITARIO EURO AMERICANO - UNIEURO,28042,23524.0,4518.0,16.11
20388,ESCOLA LA SALLE,25561,21230.0,4331.0,16.94
20445,COLEGIO LEONARDO DA VINCI,23029,18744.0,4285.0,18.61
20389,UNICEUB,21529,17426.0,4103.0,19.06
20111,CENTRO EDUCACIONAL LEONARDO DA VINCI,19545,15808.0,3737.0,19.12
20502,CENTRO EDUCACIONAL CATOLICA DE BRASILIA,19298,15238.0,4060.0,21.04
20473,UNIPLAN -CENTRO UNIVERSITÁRIO PLANALTO DO DIST...,18638,15600.0,3038.0,16.30
20115,CEM 02 - CENTRO DE ENSINO MEDIO 02 DO GAMA,18409,15076.0,3333.0,18.11
20582,CCI SÊNIOR,18178,15238.0,2940.0,16.17
20208,CENTRO EDUCACIONAL 3,17119,14314.0,2805.0,16.39
20261,COLEGIO CIMAN,16621,14160.0,2461.0,14.81
20277,ESCOLA DAS NACOES,16247,13448.0,2799.0,17.23
20307,CENTRO DE ENSINO MÉDIO 804 DO RECANTO DAS EMAS,15464,12130.0,3334.0,21.56
20203,CEMAB - CENTRO DE ENSINO MÉDIO AVE BRANCA,15423,12580.0,2843.0,18.43
20232,COLÉGIO PRESBITERIANO MACKENZIE,15173,12210.0,2963.0,19.53
20434,CEM 01 - CENTRO DE ENSINO MEDIO 01 DO GAMA,15092,12294.0,2798.0,18.54
20650,CENTRO DE ENSINO FUNDAMENTAL 25 (CENTRO EDUCAC...,14999,11672.0,3327.0,22.18
20104,CEF 01 - CENTRO DE ENSINO FUNDAMENTAL 01 DO GAMA,14528,11714.0,2814.0,19.37
20590,CENTRO DE ENSINO FUNDAMENTAL DRA. ZILDA ARNS,14326,10522.0,3804.0,26.55
20385,ESCOLA CLASSE 66,14300,10986.0,3314.0,23.17
20492,CENTRO EDUCACIONAL JARDINS MANGUEIRAL,14145,12298.0,1847.0,13.06
20145,CENTRO DE ENSINO MEDIO 01 - GINÁSIO,14141,11718.0,2423.0,17.13
20521,COLEGIO COC LAGO NORTE,14138,11794.0,2344.0,16.58
20325,COLEGIO ROGACIONISTA,14079,11656.0,2423.0,17.21
20351,CENTRO ENSINO EDUCACIONAL 01 - VILA ESTRUTURAL...,14065,10884.0,3181.0,22.62
20383,ESCOLA CLASSE 108,13852,11504.0,2348.0,16.95
20512,COLÉGIO MARISTA - ÁGUAS CLARAS,13765,11956.0,1809.0,13.14
20506,INSTITUTO FEDERAL DE BRASÍLIA - IFB SÃO SEBASTIÃO,13727,10830.0,2897.0,21.10
20396,COLÉGIO OBJETIVO - RUA 03,13709,11220.0,2489.0,18.16
20401,CENTRO DE ENSINO MÉDIO 05,13701,11456.0,2245.0,16.39
20183,CED 08 - CENTRO EDUCACIONAL 08 DO GAMA,13698,11166.0,2532.0,18.48
20398,CENTRO DE ENSINO FUNDAMENTAL 02 - VILA ESTRUTURAL,13600,9766.0,3834.0,28.19
20234,ESCOLA CLASSE 08 (ANTIGO CEF 07),13565,11124.0,2441.0,17.99
20219,CENTRO DE ENSINO MÉDIO 01 - CENTRÃO,13477,10668.0,2809.0,20.84
20228,MAPLE BEAR ( ANTIGO CANDANGUINHO - CECAN ),13285,11186.0,2099.0,15.80
20500,CENTRO DE ENSINO FUNDAMENTAL SANTOS DUMONT,13238,10796.0,2442.0,18.45
20153,CENTRO EDUCACIONAL 03 - CCM,13235,10752.0,2483.0,18.76
20468,CENTRO DE ENSINO MÉDIO 414,13071,11058.0,2013.0,15.40
20672,CENTRO EDUCACIONAL DONA AMÉRICA GUIMARÃES,12988,9702.0,3286.0,25.30
20266,CASA THOMAS JEFFERSON,12767,10684.0,2083.0,16.32
20112,COLEGIO LA SALLE,12745,10290.0,2455.0,19.26
20283,CENTRO DE ENSINO FUNDAMENTAL 308 DE SANTA MARIA,12647,9980.0,2667.0,21.09
20361,COLÉGIO LICEU,12598,10052.0,2546.0,20.21
20258,CENTRO DE ENSINO MÉDIO 09,12559,10400.0,2159.0,17.19
20245,CENTRO ENS MÉDIO EIT,12534,10302.0,2232.0,17.81
20207,CENTRO EDUCACIONAL 02,12493,10266.0,2227.0,17.83
20546,COLÉGIO DO SOL,12437,10166.0,2271.0,18.26
20220,CENTRO DE ENSINO MÉDIO 02,12351,9822.0,2529.0,20.48
20549,CENTRO DE ENSINO MÉDIO 304,12260,10040.0,2220.0,18.11
20154,CENTRO EDUCACIONAL 14 (ANTIGO CE 15),12244,10018.0,2226.0,18.18

In [16]:
abstencao_local.to_excel(
    "/content/tse2026/csv/abstencao_por_escola.xlsx",
    index=False
)

print("Excel salvo")

Excel salvo

Coordenadas dos Locais de Votação - Facilitar para fazer os mapas

In [17]:
# --------------------------------------------------
# COORDENADAS DOS LOCAIS DE VOTAÇÃO
# --------------------------------------------------

import pandas as pd

with zf_locais.open(
    "eleitorado_local_votacao_2026_BRASIL.csv"
) as f:

    coordenadas = pd.read_csv(
        f,
        sep=";",
        encoding="latin1",
        usecols=[
            "SG_UF",
            "CD_MUNICIPIO",
            "NM_MUNICIPIO",
            "NR_ZONA",
            "NR_LOCAL_VOTACAO",
            "NM_LOCAL_VOTACAO",
            "DS_ENDERECO",
            "NM_BAIRRO",
            "NR_LATITUDE",
            "NR_LONGITUDE"
        ]
    )

# elimina duplicidades de seção
coordenadas = coordenadas.drop_duplicates(
    subset=[
        "SG_UF",
        "CD_MUNICIPIO",
        "NR_ZONA",
        "NR_LOCAL_VOTACAO"
    ]
).copy()

# converte coordenadas
coordenadas["NR_LATITUDE"] = (
    coordenadas["NR_LATITUDE"]
    .astype(str)
    .str.replace(",", ".", regex=False)
)

coordenadas["NR_LONGITUDE"] = (
    coordenadas["NR_LONGITUDE"]
    .astype(str)
    .str.replace(",", ".", regex=False)
)

coordenadas["NR_LATITUDE"] = pd.to_numeric(
    coordenadas["NR_LATITUDE"],
    errors="coerce"
)

coordenadas["NR_LONGITUDE"] = pd.to_numeric(
    coordenadas["NR_LONGITUDE"],
    errors="coerce"
)

print("Locais únicos:", len(coordenadas))

print(
    "Locais com coordenadas:",
    coordenadas[
        ["NR_LATITUDE","NR_LONGITUDE"]
    ]
    .notna()
    .all(axis=1)
    .sum()
)

display(coordenadas.head(20))

Locais únicos: 96778
Locais com coordenadas: 96778

,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_LOCAL_VOTACAO,NM_LOCAL_VOTACAO,DS_ENDERECO,NM_BAIRRO,NR_LATITUDE,NR_LONGITUDE
0,SP,69795,RIO CLARO,288,1228,EM JOVELINA MORATELI,"RUA 9 MP, S/N",PARQUE MAE PRETA,-22.373419,-47.539325
1,SP,67890,OSASCO,276,1066,EE. PROFª. MARIA AUGUSTA SIQUEIRA,"RUA ANTONIO FESTA, 35",JARDIM ILONA,-23.517409,-46.757495
2,SP,67890,OSASCO,276,1090,EE. PROF. ALCYR OLIVEIRA PORCIÚNCULA,"AV. PRESIDENTE MÉDICI, 2386",JARDIM MUTINGA,-23.506368,-46.767773
3,BA,35130,EUCLIDES DA CUNHA,102,1074,COLÉGIO MODELO JOAQUIM SILVA DANTAS,"RUA TEAGO FERREIRA DE CARVALHO, SN - ZONA URBANA",CENTRO,-10.503446,-39.013297
4,SP,66397,LIMEIRA,66,1660,CENTRO EDUCACIONAL SESI 408,"AV. MAJOR LEVY SOBRINHO, 2415",BOA VISTA,-22.552158,-47.380195
5,SP,66079,JAÚ,63,1104,EE. FREI GALVÃO,"RUA SÃO JOSÉ, 242 - CENTRO",DISTRITO DE POTUNDUVA,-22.366484,-48.673651
6,MT,90670,CUIABÁ,1,2623,ESCOLA ESTADUAL PROFESSOR ULISSES CUIABANO,"RUA DOS MIOSOTIS, 555",JARDIM CUIABÁ,-15.595459,-56.118817
7,CE,15920,IBICUITINGA,47,1031,CRAS- CENTRO DE REFERENCIA DA AÇÃO SOCIAL,RUA JOAO DUARTE 2212,CENTRO,-4.976468,-38.636565
8,SP,71072,SÃO PAULO,422,1074,E.E. GUILHERME DE ALMEIDA,"AVENIDA PARADA PINTO, 2355",VILA AMALIA (ZONA NORTE),-23.469232,-46.648765
9,SP,71072,SÃO PAULO,349,1171,EE. CÔNEGO JOÃO LIGABUE,"RUA DA GROTA, 483",VILA GUSTAVO,-23.481871,-46.596192
10,MG,49174,OURO BRANCO,88,1210,COLEGIO ARQUIDIOCESANO DE OURO BRANCO,"RUA CARLOS WIGG, 245",PIONEIROS,-29.972402,-50.134103
11,SE,31771,MALHADOR,26,1120,PROFESSORA LENA - ESCOLA MUNICIPAL ELINALDA DO...,POVOADO PALMEIRAS,"PALMEIRAS, POVOADO",-10.683255,-37.304404
12,SC,80390,BALNEÁRIO CAMBORIÚ,103,1031,UNIVALI - UNIVERSIDADE DO VALE DO ITAJAI - CAM...,"QUINTA AVENIDA, 1100",MUNICIPIOS,-27.004946,-48.635510
13,RS,88455,SANT'ANA DO LIVRAMENTO,30,1147,ESCOLA ESTADUAL GENERAL NETO,"RUA SALGADO FILHO, 604",CENTRO,-30.888893,-55.537774
14,GO,92215,ANÁPOLIS,3,1562,COLÉGIO ESTADUAL AMERICO BORGES DE CARVALHO - ...,RUA BELA VISTA SN,JARDIM GOIANO,-16.335207,-48.965651
15,SP,71072,SÃO PAULO,2,1090,FAAP - FUNDAÇÃO ARMANDO ÁLVARES PENTEADO,"RUA ALAGOAS, 903",HIGIENOPOLIS,-23.544646,-46.662436
16,AM,2550,MANAUS,70,1953,E. E. BELARMINO MARREIRO,"RUA JUNQUEIRA, S/N CONJ. ARCO-ÍRIS",NOVO ALEIXO,-3.050817,-59.964346
17,AM,2550,MANAUS,70,1996,E. E. WILMA VITORIANO GEBER,"RUA MARCOS CAVALCANTE, 121, ALFREDO NASCIMENTO",CIDADE DE DEUS,-3.014472,-59.954667
18,SP,64157,FERRAZ DE VASCONCELOS,401,1163,EE. PROF. PAULO AMÉRICO PAGANUCCI,"RUA QUINZE DE NOVEMBRO, 2366",CAMBIRI,-23.557965,-46.358864
19,SP,62910,CAMPINAS,274,1724,EE. DR. DISNEI FRANCISCO SCORNAIENCHI,"RUA EDMUNDO VOSGRAU, 515",PARQUE JAMBEIRO,-22.959377,-47.052868

In [18]:
coordenadas.to_csv(
    "/content/tse2026/csv/coordenadas_escolas_tse.csv",
    index=False,
    encoding="utf-8-sig"
)

print(
    "/content/tse2026/csv/coordenadas_escolas_tse.csv"
)

/content/tse2026/csv/coordenadas_escolas_tse.csv

Coordenadas de outros países não aparecem como válidas

In [19]:
problemas = coordenadas[
    (~coordenadas["NR_LATITUDE"].between(-34,6))
    |
    (~coordenadas["NR_LONGITUDE"].between(-75,-32))
]

print("Coordenadas suspeitas:", len(problemas))

display(
    problemas.head(50)
)

Coordenadas suspeitas: 1257

,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_LOCAL_VOTACAO,NM_LOCAL_VOTACAO,DS_ENDERECO,NM_BAIRRO,NR_LATITUDE,NR_LONGITUDE
692,ZZ,39063,VANCOUVER,1,1031,PINNACLE HOTEL HARBOURFRONT - VANCOUVER - COLÚ...,"1133 W HASTINGS ST, VANCOUVER, BC V6E 3T3",CANADA,-1.0,-1.0
1189,ZZ,29416,BOSTON,1,1112,ST TARCISUS PARISH,"562 WAVERLY ST, FRAMINGHAM, MA 01702",CENTRO,-1.0,-1.0
1212,ZZ,29971,LONDRES,1,1015,WEST LONDON COLLEGE,"9 GLIDDON RD, HAMMERSMITH, LONDON W14 9BL",INGLATERRA,-1.0,-1.0
1232,ZZ,30287,PARIS,1,1066,ESPACE VINCI,"25 RUE DES JEUNEURS, 75002 PARIS",CENTRO,-1.0,-1.0
1435,MG,48755,MUNHOZ,112,1015,E.M.E.I. PROFESSORA MARIA ALBA DE FREITAS,"RUA MINAS GERAIS, S/N",CENTRO,-1.0,-1.0
1972,PB,21199,PAULISTA,69,1139,CRECHE ROBSON DE ARAÚJO VERAS,RUA JOSÉ PEDRO DE OLIVEIRA VENTURA,PADRE SOLON,-1.0,-1.0
2580,PI,10456,CANTO DO BURITI,36,1341,UE GALDINO JOSÉ DA COSTA,LOCALIDADE GAVIÃO,ZONA RURAL,-1.0,-1.0
2699,ZZ,30619,TEL AVIV,1,1015,EMBAIXADA DO BRASIL EM TEL AVIV,"DERECH BEGIN, N. 23, 28 ANDAR - TEL AVIV",ISRAEL,-1.0,-1.0
2841,ZZ,30562,SYDNEY,1,1031,BRISBANE CITY HALL,"64 ADELAIDE ST, BRISBANE CITY, 4000",AUSTRALIA,-1.0,-1.0
3226,RR,3000,CAROEBE,4,1147,ESCOLA MUNICIPAL MARIA QVEDO,"AV. BAHIA, S/N - CENTRO",CENTRO,-1.0,-1.0
3434,ZZ,99490,ORLANDO,1,1015,OSCEOLA HERITAGE PARK,"1875 SILVER SPUR LN, KISSIMMEE, FL 34744",CENTRO,-1.0,-1.0
3491,SP,69990,SALES OLIVEIRA,81,1031,EE CAPITÃO GETÚLIO LIMA,"RUA VEREADOR OMAR ROCHA, 174",CENTRO,-1.0,-1.0
3561,RS,87866,SÃO VALÉRIO DO SUL,107,1090,I. E. E. I. ÂNGELO MANHKA MIGUEL,TERRA INDÍGENA INHACORÁ - SETOR VILA NOVA,INTERIOR,-1.0,-1.0
3660,BA,35254,GENTIO DO OURO,68,1244,COLÉGIO ESTADUAL MARIA QUITÉRIA,RUA EDMUNDO PEREIRA BASTOS - ZONA URBANA,CENTRO,-1.0,-1.0
3752,ZZ,30627,TÓQUIO,1,1023,ARIAKE CENTRAL TOWER,"135-0063, TOKYO-TO, KOTO-KU, ARIAKE 3-7-18, 3...",CENTRO,-1.0,-1.0
3753,ZZ,30120,MILÃO,1,1040,SELEXI TEST CENTER,"VIA DEI VALTORTA, 48, 20127, MILÃO (MI), ITÁLIA",CENTRO,-1.0,-1.0
4215,ZZ,30341,PORTO,1,1015,ISEP - R. DR. ANTONIO BERNARDINO / R. DE SÃO T...,SEÇÃO 1431 A 2957 (R. ANTONIO BERNARD) SEÇÃO 3...,PORTUGAL,-1.0,-1.0
4735,RR,3107,UIRAMUTÃ,7,1236,SECRETARIA MUNICIPAL DE EDUCAÇÃO,"RUA CECIR MOTA, S/N - SEDE",CENTRO,-1.0,-1.0
4784,ZZ,29351,BARCELONA,1,1015,SEMINARI CONCILIAR DE BARCELONA,"CARRER DE LA DIPUTACIÓ, 231, EIXAMPLE, 08007, ...",ESPANHA,-1.0,-1.0
5191,ZZ,29300,ARGEL,1,1015,EMBAIXADA DO BRASIL EM ARGEL,"55, BIS CHEMIN CHEIKH BACHIR EL IBRAHIMI, EL B...",ARGÉLIA,-1.0,-1.0
5242,MG,46930,JACINTO,144,1104,ESCOLA MUNICIPAL SILVÁRIO JOSÉ DE ALMEIDA,"RUA VEREADOR FULGÊNCIO ALMEIDA, 604",DISTRITO DE JAGUARÃO,-1.0,-1.0
5483,ZZ,30112,MIAMI,1,1058,MIAMI DADE COLLEGE - KENDALL CAMPUS,"11011 SW 104TH STREET - MIAMI, FL33176 BUILDIN...",CENTRO,-1.0,-1.0
5673,ZZ,30562,SYDNEY,1,1015,SEÇÕES 1950/1954/1955/1956/1957 VOTAM NO CONSU...,DEMAIS SEÇÕES VOTAM EM 10 SPRING STREET,AUSTRALIA,-1.0,-1.0
5800,ZZ,30066,MADRI,1,1023,COLÉGIO BLANCA DE CASTILLA,"PASEO DE EDUARDO DATO, 2, MADRI",ESPANHA,-1.0,-1.0
6313,ZZ,30635,TORONTO,1,1066,YMCA CENTRE-TORONTO - ONTÁRIO,"20 GROSVENOR ST, TORONTO, ON",CANADA,-1.0,-1.0
6314,ZZ,29955,LISBOA,1,1080,"UNIVERSIDADE DE LISBOA (REITORIA, FAC. DIREITO...","ALAMEDA DA UNIVERSIDADE, CIDADE UNIVERSITÁRIA,...",PORTUGAL,-1.0,-1.0
6456,MT,91049,SANTA RITA DO TRIVELATO,5,1031,ESCOLA ESTADUAL CANDIDO PORTINARI,CENTRO,CENTRO,-1.0,-1.0
6546,ZZ,29416,BOSTON,1,1023,SALEMWOOD SCHOOL,"529 SALEM ST, MALDEN, MA 02148",CENTRO,-1.0,-1.0
6820,BA,35254,GENTIO DO OURO,68,1090,PREDIO ESCOLAR MUNICIPAL JOSE LACERDA,RUA DO PREDIO ESCOLAR - ZONA RURAL,POVOADO COTOVELO,-1.0,-1.0
7115,SP,66770,MARACAÍ,290,1090,CRECHE ESCOLA ELIANA GORETI DE ANDRADE,RUA OZÓRIO REGINALDO DE SOUZA,JARDIM SANTA OLGA,-1.0,-1.0
7189,SP,71072,SÃO PAULO,258,1899,EMEI PROFESSORA ISABEL COLOMBO,"AV. PADRE ANTÔNIO JOSÉ DOS SANTOS, 1511",CIDADE MONÇÕES,-1.0,-1.0
7205,ZZ,29807,HOUSTON,1,1023,NORIS CONFERENCE CENTER/CITY CENTER,"816 TOWN AND COUNTRY BLVD 210, HOUSTON, TEXAS ...",ESTADOS UNIDOS,-1.0,-1.0
7424,ZZ,29432,BRUXELAS,1,1015,BRUXELAS - PREFEITURA DE SAINT-GILLES (HÔTEL D...,"PLACE MAURICE VAN MEENEN 39, SAINT-GILLES, 1060",BÉLGICA,-1.0,-1.0
7505,PA,4154,ANANINDEUA,43,2615,SISTEMA DE ENSINO PEQUENO PRINCIPE,"TV COLETORA LESTE, RUA 14, 26",ÁGUAS LINDAS,-1.0,-1.0
7537,MT,91294,POCONÉ,4,1570,CMEI AUGUSTA LEITE,RUA NOSSA SENHORA DO CARMO,CRUZ PRETA,-1.0,-1.0
7595,RS,87246,NOVA SANTA RITA,66,1163,E.M.E.F. PROFESSORA JANAÍNA PEREIRA,"PORTO DA FARINHA, 821",CAJU,-1.0,-1.0
7605,ZZ,29955,LISBOA,1,1031,"UNIVERSIDADE DE LISBOA (REITORIA, FAC. DIREITO...","ALAMEDA DA UNIVERSIDADE, CIDADE UNIVERSITÁRIA,...",PORTUGAL,-1.0,-1.0
8451,ZZ,99295,PYONGYANG,1,1015,PYONGYANG,EMBAIXADA DO BRASIL EM PYONGYANG,CENTRO,-1.0,-1.0
8564,ZZ,30449,ROMA,1,1015,EMBAIXADA DO BRASIL EM ROMA,"PIAZZA NAVONA 14, ROMA, ITÁLIA",ITÁLIA,-1.0,-1.0
9234,ZZ,30783,WASHINGTON,1,1031,CAPITAL HILTON (HOTEL),"1001 16TH STREET NW, WASHINGTON DC, 20036, EST...",ESTADOS UNIDOS,-1.0,-1.0
9515,SP,64890,IBIRÁ,179,1090,ESCOLA MUNICIPAL PROFª EDITH PEREIRA GONZAGA,"R. ADRIANO PINHO MAIA, 470",SÃO BENEDITO,-1.0,-1.0
9558,PA,4359,BREVES,15,2070,EMEF RAIMUNDO PINHEIRO,AVENIDA MUANÁ 3379 - ZONA URBANA,CIDADE NOVA II,-1.0,-1.0
10444,ZZ,29262,ABU DHABI,1,1015,CHANCELARIA DA EMBAIXADA EM ABU DHABI,"AL BATEEN GARDENS, C3 TOWER, ABU DHABI, PO BOX...",EMIRADOS ÁRABES,-1.0,-1.0
10656,ZZ,30473,SANTA CRUZ DE LA SIERRA,1,1015,CONSULADO EM SANTA CRUZ DE LA SIERRA,"AVENIDA MARCELO TERCEROS BANZER 334, SANTA CRU...",BOLÍVIA,-1.0,-1.0
10828,RR,3107,UIRAMUTÃ,7,1279,ESCOLA ESTADUAL INDÍGENA TUXAUA CRETÁCIO,COMUNIDADE MAPAÉ,Comunidade Mapaé,-1.0,-1.0
11088,MG,47015,JANAÚBA,147,1520,PRESÍDIO DE JANAÚBA,"RUA MANOEL BANDEIRA, 350",VEREDAS,-1.0,-1.0
11379,PB,22390,UIRAÚNA,53,1619,SECRETARIA DE SAÚDE,"RUA POETA FRANCISCO EVARISTO, S/N",RETIRO I,-1.0,-1.0
11494,ZZ,29270,ACCRA,1,1015,EMBAIXADA DO BRASIL EM ACRA,"TEMPLESI LANE 1, AIRPORT RESIDENTIAL AREA, ACR...",GANA,-1.0,-1.0
11561,RS,88234,ROLANTE,55,1546,E.M.E.F. PRINCESA ISABEL,"EST FAZENDA PASSOS , 2598",FAZENDA PASSOS,-1.0,-1.0
11606,ZZ,30333,PORTO PRÍNCIPE,1,1015,INSTITUTO GUIMARÃES ROSEA (IGR) - CENTRE CULTU...,"168, RUE DARGUIN, PÉTION-VILLE",HAITI,-1.0,-1.0

In [20]:
import plotly.express as px

pontos = coordenadas.dropna(
    subset=[
        "NR_LATITUDE",
        "NR_LONGITUDE"
    ]
)

fig = px.scatter_geo(
    pontos.sample(
        min(
            5000,
            len(pontos)
        )
    ),
    lat="NR_LATITUDE",
    lon="NR_LONGITUDE",
    hover_name="NM_LOCAL_VOTACAO",
    hover_data=[
        "NM_MUNICIPIO",
        "NM_BAIRRO"
    ],
    title="Amostra dos Locais de Votação do TSE"
)

fig.show()

Agragar votos por escola

In [21]:
votos_escola = (

    votos

    .groupby(
        [
            "SG_UF",
            "CD_MUNICIPIO",
            "NR_LOCAL_VOTACAO",
            "NM_LOCAL_VOTACAO",
            "NM_VOTAVEL"
        ],
        as_index=False
    )

    ["QT_VOTOS"]

    .sum()

)

print(votos_escola.shape)

display(votos_escola.head())

(825054, 6)

,SG_UF,CD_MUNICIPIO,NR_LOCAL_VOTACAO,NM_LOCAL_VOTACAO,NM_VOTAVEL,QT_VOTOS
0,AC,1007,1023,ESCOLA JOSE CEZARIO DE FARIAS,AUGUSTO JORGE CURY,15
1,AC,1007,1023,ESCOLA JOSE CEZARIO DE FARIAS,CLARIANA ZACARKIM BARAO,1
2,AC,1007,1023,ESCOLA JOSE CEZARIO DE FARIAS,EDMILSON SILVA COSTA,2
3,AC,1007,1023,ESCOLA JOSE CEZARIO DE FARIAS,FLAVIO NANTES BOLSONARO,735
4,AC,1007,1023,ESCOLA JOSE CEZARIO DE FARIAS,LUIZ INÁCIO LULA DA SILVA,275

In [22]:
votos_wide = votos_escola.pivot_table(

    index=[
        "SG_UF",
        "CD_MUNICIPIO",
        "NR_LOCAL_VOTACAO",
        "NM_LOCAL_VOTACAO"
    ],

    columns="NM_VOTAVEL",

    values="QT_VOTOS",

    aggfunc="sum",

    fill_value=0

).reset_index()

print(votos_wide.shape)

display(votos_wide.head())

(95127, 19)

NM_VOTAVEL,SG_UF,CD_MUNICIPIO,NR_LOCAL_VOTACAO,NM_LOCAL_VOTACAO,AUGUSTO JORGE CURY,CLARIANA ZACARKIM BARAO,EDMILSON SILVA COSTA,FLAVIO NANTES BOLSONARO,HERTZ DA CONCEICAO DIAS,LEONARDO ALVES DE ARAUJO,LUIZ INÁCIO LULA DA SILVA,RENAN ANTONIO FERREIRA DOS SANTOS,ROMEU ZEMA NETO,RONALDO RAMOS CAIADO,RUI COSTA PIMENTA,SAMARA MARTINS DA SILVA FEITOSA,VOTO BRANCO,VOTO NULO,WILSON GRASSI JUNIOR
0,AC,1007,1023,ESCOLA JOSE CEZARIO DE FARIAS,15,1,2,735,0,0,275,6,0,13,0,1,17,37,0
1,AC,1007,1040,ESCOLA MAPINGUARI - FUNTAC - PROJETO ANTIMARI,2,0,0,136,0,0,15,0,0,0,0,0,1,2,0
2,AC,1007,1058,"NÚCLEO DE EDUCAÇÃO, CULTURA E ESPORTES - SEE -...",19,0,0,452,0,0,220,3,0,15,0,0,6,17,0
3,AC,1007,1066,ESCOLA RURAL NOVA VIDA,5,0,0,202,0,0,143,6,0,5,0,0,5,9,0
4,AC,1007,1074,ESCOLA RURAL MARIA DO CARMO RAMOS,3,0,0,218,0,0,24,1,0,4,0,0,0,7,0

In [23]:
mapa_final = coordenadas.merge(

    abstencao_local,

    on=[
        "SG_UF",
        "CD_MUNICIPIO",
        "NR_LOCAL_VOTACAO",
        "NM_LOCAL_VOTACAO"
    ],

    how="inner"

)

mapa_final = mapa_final.merge(

    votos_wide,

    on=[
        "SG_UF",
        "CD_MUNICIPIO",
        "NR_LOCAL_VOTACAO",
        "NM_LOCAL_VOTACAO"
    ],

    how="left"

)

print(mapa_final.shape)

display(mapa_final.head())

(96778, 30)

,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO_x,NR_ZONA,NR_LOCAL_VOTACAO,NM_LOCAL_VOTACAO,DS_ENDERECO,NM_BAIRRO,NR_LATITUDE,NR_LONGITUDE,...,LEONARDO ALVES DE ARAUJO,LUIZ INÁCIO LULA DA SILVA,RENAN ANTONIO FERREIRA DOS SANTOS,ROMEU ZEMA NETO,RONALDO RAMOS CAIADO,RUI COSTA PIMENTA,SAMARA MARTINS DA SILVA FEITOSA,VOTO BRANCO,VOTO NULO,WILSON GRASSI JUNIOR
0,SP,69795,RIO CLARO,288,1228,EM JOVELINA MORATELI,"RUA 9 MP, S/N",PARQUE MAE PRETA,-22.373419,-47.539325,...,0.0,708.0,75.0,8.0,53.0,0.0,3.0,72.0,131.0,0.0
1,SP,67890,OSASCO,276,1066,EE. PROFª. MARIA AUGUSTA SIQUEIRA,"RUA ANTONIO FESTA, 35",JARDIM ILONA,-23.517409,-46.757495,...,0.0,1760.0,101.0,12.0,111.0,3.0,8.0,115.0,163.0,0.0
2,SP,67890,OSASCO,276,1090,EE. PROF. ALCYR OLIVEIRA PORCIÚNCULA,"AV. PRESIDENTE MÉDICI, 2386",JARDIM MUTINGA,-23.506368,-46.767773,...,1.0,2079.0,164.0,13.0,104.0,2.0,7.0,136.0,209.0,1.0
3,BA,35130,EUCLIDES DA CUNHA,102,1074,COLÉGIO MODELO JOAQUIM SILVA DANTAS,"RUA TEAGO FERREIRA DE CARVALHO, SN - ZONA URBANA",CENTRO,-10.503446,-39.013297,...,0.0,718.0,16.0,0.0,11.0,0.0,0.0,11.0,30.0,0.0
4,SP,66397,LIMEIRA,66,1660,CENTRO EDUCACIONAL SESI 408,"AV. MAJOR LEVY SOBRINHO, 2415",BOA VISTA,-22.552158,-47.380195,...,1.0,245.0,36.0,7.0,14.0,1.0,1.0,16.0,31.0,0.0

In [24]:
col_lula = [c for c in mapa_final.columns if "LULA" in c.upper()][0]

col_bol = [c for c in mapa_final.columns if "BOLSONARO" in c.upper()][0]

print("Lula:", col_lula)
print("Bolsonaro:", col_bol)

Lula: LUIZ INÁCIO LULA DA SILVA
Bolsonaro: FLAVIO NANTES BOLSONARO

In [25]:
mapa_final["TOTAL_VOTOS"] = (

    mapa_final["COMPARECIMENTO"]

)

mapa_final["PCT_LULA"] = (

    100

    * mapa_final[col_lula]

    / mapa_final["COMPARECIMENTO"]

).round(2)

mapa_final["PCT_BOLSONARO"] = (

    100

    * mapa_final[col_bol]

    / mapa_final["COMPARECIMENTO"]

).round(2)

mapa_final["MARGEM"] = (

    mapa_final["PCT_LULA"]

    -

    mapa_final["PCT_BOLSONARO"]

).round(2)

In [26]:
mapa_final.columns.tolist()

['SG_UF',
 'CD_MUNICIPIO',
 'NM_MUNICIPIO_x',
 'NR_ZONA',
 'NR_LOCAL_VOTACAO',
 'NM_LOCAL_VOTACAO',
 'DS_ENDERECO',
 'NM_BAIRRO',
 'NR_LATITUDE',
 'NR_LONGITUDE',
 'NM_MUNICIPIO_y',
 'QT_ELEITOR_ELEICAO_FEDERAL',
 'COMPARECIMENTO',
 'ABSTENCAO',
 'PCT_ABSTENCAO',
 'AUGUSTO JORGE CURY',
 'CLARIANA ZACARKIM BARAO',
 'EDMILSON SILVA COSTA',
 'FLAVIO NANTES BOLSONARO',
 'HERTZ DA CONCEICAO DIAS',
 'LEONARDO ALVES DE ARAUJO',
 'LUIZ INÁCIO LULA DA SILVA',
 'RENAN ANTONIO FERREIRA DOS SANTOS',
 'ROMEU ZEMA NETO',
 'RONALDO RAMOS CAIADO',
 'RUI COSTA PIMENTA',
 'SAMARA MARTINS DA SILVA FEITOSA',
 'VOTO BRANCO',
 'VOTO NULO',
 'WILSON GRASSI JUNIOR',
 'TOTAL_VOTOS',
 'PCT_LULA',
 'PCT_BOLSONARO',
 'MARGEM']

In [27]:
mapa_final["NM_MUNICIPIO"] = mapa_final["NM_MUNICIPIO_x"]

In [29]:
mapa_final["VENCEDOR"] = mapa_final.apply(

    lambda r:
    "LULA"
    if r["LUIZ INÁCIO LULA DA SILVA"]
    >
    r["FLAVIO NANTES BOLSONARO"]

    else

    "BOLSONARO",

    axis=1
)

In [30]:
color="VENCEDOR"

In [31]:
color="PCT_ABSTENCAO"

In [32]:
# Corrige todos os NaN das colunas numéricas

cols_num = [
    "QT_ELEITOR_ELEICAO_FEDERAL",
    "COMPARECIMENTO",
    "ABSTENCAO",
    "PCT_ABSTENCAO",
    "LUIZ INÁCIO LULA DA SILVA",
    "FLAVIO NANTES BOLSONARO",
    "VOTO BRANCO",
    "VOTO NULO"
]

for c in cols_num:
    if c in mapa_final.columns:
        mapa_final[c] = mapa_final[c].fillna(0)

In [34]:
!pip install folium -q

In [36]:
mapa_final = mapa_final[
    mapa_final["QT_ELEITOR_ELEICAO_FEDERAL"] > 0
].copy()

mapa_final = mapa_final.drop_duplicates(
    subset=[
        "SG_UF",
        "CD_MUNICIPIO",
        "NR_LOCAL_VOTACAO"
    ]
)

In [37]:
print("Escolas:", len(mapa_final))

Escolas: 83679

In [38]:
# Remove duplicidades
mapa_final = mapa_final.drop_duplicates(
    subset=[
        "SG_UF",
        "CD_MUNICIPIO",
        "NR_LOCAL_VOTACAO"
    ]
)

# Corrige todos os NaN numéricos
for col in mapa_final.columns:

    if mapa_final[col].dtype in ["float64","int64"]:

        mapa_final[col] = mapa_final[col].fillna(0)

print(mapa_final.shape)

(83679, 36)

In [39]:
def inteiro(x):
    try:
        return f"{int(x):,}".replace(",", ".")
    except:
        return "0"

In [40]:
import folium

m = folium.Map(

    location=[-15,-55],

    zoom_start=4,

    tiles="OpenStreetMap",

    control_scale=True

)

In [41]:
for _, r in mapa_final.iterrows():

    popup = f"""
    <b>{r['NM_LOCAL_VOTACAO']}</b>

    <br><br>

    Município:
    {r['NM_MUNICIPIO_x']}

    <br>

    Bairro:
    {r['NM_BAIRRO']}

    <hr>

    Aptos:
    {inteiro(r['QT_ELEITOR_ELEICAO_FEDERAL'])}

    <br>

    Comparecimento:
    {inteiro(r['COMPARECIMENTO'])}

    <br>

    Abstenção:
    {inteiro(r['ABSTENCAO'])}

    <br>

    % Abstenção:
    {r['PCT_ABSTENCAO']:.2f}

    <hr>

    Lula:
    {inteiro(r['LUIZ INÁCIO LULA DA SILVA'])}

    <br>

    Bolsonaro:
    {inteiro(r['FLAVIO NANTES BOLSONARO'])}

    <br>

    Branco:
    {inteiro(r['VOTO BRANCO'])}

    <br>

    Nulo:
    {inteiro(r['VOTO NULO'])}
    """

    folium.CircleMarker(

        location=[
            r["NR_LATITUDE"],
            r["NR_LONGITUDE"]
        ],

        radius=4,

        weight=1,

        fill=True,

        popup=popup

    ).add_to(m)

In [43]:
# remove problemas de merge
mapa_final["NM_MUNICIPIO"] = (
    mapa_final["NM_MUNICIPIO_x"]
    .fillna(mapa_final["NM_MUNICIPIO_y"])
)

# remove coordenadas inválidas
mapa_final = mapa_final.dropna(
    subset=["NR_LATITUDE", "NR_LONGITUDE"]
)

# limites Brasil
mapa_final = mapa_final[
    mapa_final["NR_LATITUDE"].between(-34, 6)
]

mapa_final = mapa_final[
    mapa_final["NR_LONGITUDE"].between(-75, -32)
]

print(mapa_final.shape)

(82928, 36)

In [45]:
import json

geojson = {
    "type": "FeatureCollection",
    "features": []
}

for _, r in mapa_final.iterrows():

    geojson["features"].append({

        "type": "Feature",

        "geometry": {
            "type": "Point",
            "coordinates": [
                float(r["NR_LONGITUDE"]),
                float(r["NR_LATITUDE"])
            ]
        },

        "properties": {

            "escola":
                str(r["NM_LOCAL_VOTACAO"]),

            "municipio":
                str(r["NM_MUNICIPIO"]),

            "bairro":
                str(r.get("NM_BAIRRO","")),

            "aptos":
                int(r["QT_ELEITOR_ELEICAO_FEDERAL"]),

            "comparecimento":
                int(r["COMPARECIMENTO"]),

            "abstencao":
                int(r["ABSTENCAO"]),

            "pct_abstencao":
                round(float(r["PCT_ABSTENCAO"]),2),

            "lula":
                int(r["LUIZ INÁCIO LULA DA SILVA"]),

            "bolsonaro":
                int(r["FLAVIO NANTES BOLSONARO"]),

            "branco":
                int(r["VOTO BRANCO"]),

            "nulo":
                int(r["VOTO NULO"])
        }
    })

with open(
    "/content/tse2026/escolas.geojson",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        geojson,
        f,
        ensure_ascii=False
    )

print(
    "GeoJSON salvo:"
)

print(
    "/content/tse2026/escolas.geojson"
)

print(
    "Total de escolas:",
    len(geojson["features"])
)

GeoJSON salvo:
/content/tse2026/escolas.geojson
Total de escolas: 82928

In [46]:
geojson["features"][0]

{'type': 'Feature',
 'geometry': {'type': 'Point', 'coordinates': [-47.5393249, -22.373419]},
 'properties': {'escola': 'EM JOVELINA MORATELI',
  'municipio': 'RIO CLARO',
  'bairro': 'PARQUE MAE PRETA',
  'aptos': 6265,
  'comparecimento': 5114,
  'abstencao': 1151,
  'pct_abstencao': 18.37,
  'lula': 708,
  'bolsonaro': 1431,
  'branco': 72,
  'nulo': 131}}

In [47]:
import os

arquivo = "/content/tse2026/escolas.geojson"

print(
    round(
        os.path.getsize(arquivo) / 1024 / 1024,
        2
    ),
    "MB"
)

27.8 MB

REDUZIR PRA CABER NO GITHUB

In [48]:
import json
import os

geojson = {
    "type": "FeatureCollection",
    "features": []
}

for _, r in mapa_final.iterrows():

    geojson["features"].append({

        "type": "Feature",

        "geometry": {
            "type": "Point",
            "coordinates": [
                round(float(r["NR_LONGITUDE"]),5),
                round(float(r["NR_LATITUDE"]),5)
            ]
        },

        "properties": {

            "esc": str(r["NM_LOCAL_VOTACAO"]),

            "mun": str(r["NM_MUNICIPIO"]),

            "apt":
                int(r["QT_ELEITOR_ELEICAO_FEDERAL"]),

            "abs":
                int(r["ABSTENCAO"]),

            "pct":
                round(float(r["PCT_ABSTENCAO"]),1),

            "lul":
                int(r["LUIZ INÁCIO LULA DA SILVA"]),

            "bol":
                int(r["FLAVIO NANTES BOLSONARO"])

        }
    })

arquivo = "/content/tse2026/escolas_leve.geojson"

with open(
    arquivo,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        geojson,
        f,
        separators=(",", ":"),
        ensure_ascii=False
    )

print("Arquivo:", arquivo)

print(
    "Tamanho:",
    round(
        os.path.getsize(arquivo)
        /1024/1024,
        2
    ),
    "MB"
)

Arquivo: /content/tse2026/escolas_leve.geojson
Tamanho: 16.9 MB

In [49]:
print(
    len(geojson["features"])
)

geojson["features"][0]

82928

{'type': 'Feature',
 'geometry': {'type': 'Point', 'coordinates': [-47.53932, -22.37342]},
 'properties': {'esc': 'EM JOVELINA MORATELI',
  'mun': 'RIO CLARO',
  'apt': 6265,
  'abs': 1151,
  'pct': 18.4,
  'lul': 708,
  'bol': 1431}}